### ISSUE TITLE
Async support

### ISSUE THREAD

**Issue by zhenpingfeng** [mgeier/rtrb#55]
Thanks a lot for this crate. Are there any plans of adding async support?

**Comment by mgeier** [comment]
I don't currently have plans for that, but I don't know enough about async to even tell whether that would be meaningful at all.

On a conceptual level, how would async support look like?

**Comment by niXman** [comment]
@mgeier look at this workflow:
1) https://github.com/niXman/binapi/blob/master/src/api.cpp#L166
2) https://github.com/niXman/binapi/blob/master/src/api.cpp#L286
3) https://github.com/niXman/binapi/blob/master/src/api.cpp#L380
4) https://github.com/niXman/binapi/blob/master/src/api.cpp#L410
5) https://github.com/niXman/binapi/blob/master/src/api.cpp#L418
6) https://github.com/niXman/binapi/blob/master/src/api.cpp#L440
7) https://github.com/niXman/binapi/blob/master/src/api.cpp#L449
8) https://github.com/niXman/binapi/blob/master/src/api.cpp#L463
9) https://github.com/niXman/binapi/blob/master/src/api.cpp#L470
10) https://github.com/niXman/binapi/blob/master/src/api.cpp#L485
11) https://github.com/niXman/binapi/blob/master/src/api.cpp#L493
12) https://github.com/niXman/binapi/blob/master/src/api.cpp#L508
13) https://github.com/niXman/binapi/blob/master/src/api.cpp#L517
14) https://github.com/niXman/binapi/blob/master/src/api.cpp#L522
15) https://github.com/niXman/binapi/blob/master/src/api.cpp#L548
