### ISSUE TITLE
Possible data corruption?

### ISSUE THREAD

**Issue by nullchinchilla** [mgeier/rtrb#58]
In an attempt to use `rtrb` in my code (mostly through its `Read` and `Write` implementations), I've noticed that occasionally a few hundred bytes gets lost. How can I debug whether this would be a `rtrb` issue? Has `rtrb` undergone `loom`-based rigorous testing, or anything of that sort?

**Comment by mgeier** [comment]
I haven't used `loom`, but I would be interested in trying it together with `rtrb`. Do you have an idea how to create an appropriate test case (or I guess a "model" in `loom` terminology)?

Regarding the `Read` and `Write` implementations, the main thing to check is whether [std::io::ErrorKind::WouldBlock](https://doc.rust-lang.org/std/io/enum.ErrorKind.html#variant.WouldBlock) is generated and handled as expected.

If you are only using `Read` and `Write`, you could probably quickly switch `rtrb` with `ringbuf`, which also has a [`Read`](https://docs.rs/ringbuf/0.2.6/ringbuf/struct.Consumer.html#impl-Read) and [`Write`](https://docs.rs/ringbuf/0.2.6/ringbuf/struct.Producer.html#impl-Write) implementation.

**Comment by mgeier** [comment]
Any news on this @nullchinchilla?

If there indeed is data corruption, I'd like to fix that, but if there isn't, I'd like to close this issue because it might deter people from using `rtrb`.

**Comment by nullchinchilla** [comment]
So I refactored out the code that was causing issues into a separate crate: https://github.com/geph-official/bipe/blob/master/src/lib.rs

Can you take a look to see whether there are obvious problems in my code? I think what I'm doing (implementing a "blocking" asynchronous pipe) is pretty straightforward --- but what I see is that occasionally stuff in the buffer get "lost".

**Comment by nullchinchilla** [comment]
It turned out to be a bug in my code, where I called `write()` where I meant `write_all()`. My own ring-buffer implementation blocked until there was room to fulfill the *entire* write, so the bug was masked until I switched to rtrb!

**Comment by mgeier** [comment]
Thanks for the update @nullchinchilla, I'm glad you found the bug!
