### ISSUE TITLE
Add ability to query fullness

### ISSUE THREAD

**Issue by kiranshila** [mgeier/rtrb#91]
Hey! First off, thank you for this amazing crate. I'm using it for real-time data processing for a radio telescope, which works wonders.

 If possible,  I would like a function to query "percent fullness" or something to that end so I can log warnings when we get close to the end. This would help me catch cases where my consuming code can't keep up with production.

Thanks again!

**Comment by mgeier** [comment]
Can't you use `c.slots() / c.buffer().capacity()` (for a comsumer `c`, and something similar for a producer?)?

**Comment by kiranshila** [comment]
Indeed, thank you.
