### ISSUE TITLE
as_mut_slices for ReadChunk

### ISSUE THREAD

**Issue by raftario** [mgeier/rtrb#99]
For an extremely niche use case with smoltcp, from what I understand this could just be added with the current API since the ReadChunk has exclusive access to its data already

**Comment by mgeier** [comment]
Yes, I think this could be added, but I'm curious, could you quickly describe the use case?

It should be possible to get a `ReadChunk`, then *write* into it, then *not* commit it. This way, the changed data will be available the next time a `ReadChunk` is requested. Is this it?

Or do you just nominally need the `ReadChunk` to be writable, without actually writing to it?

**Comment by raftario** [comment]
I just nominally need it to be writable, I'd assume given smoltcp is no_std it probably uses the read buffer you provide it to perform some decoding operations in place or something similar
